services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  postgres2:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
  # prisma:
  #   image: prismagraphql/prisma:1.34
  #   restart: always
  #   ports:
  #     - "4466:4466"
  #   environment:
  #     PRISMA_CONFIG: |
  #       port: 4466
  #       databases:
  #         default:
  #           connector: postgres
  #           host: postgres
  #           port: 5432
  #           user: postgres
  #           password: postgres
  #           migrations: postgres
  # prisma-studio:
  #   image: prismagraphql/prisma:1.34
  #   command: ["npx", "prisma", "studio"]
  #   restart: always
  #   ports:
  #     - "5555:5555"
  #   environment:
  #     DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres
  #   depends_on:
  #     - postgres